# Generated by Django 4.1.3 on 2024-02-13 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_remove_employee_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
