# Generated by Django 4.1.3 on 2024-02-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_employee_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('coding', 'Coding'), ('graphics', 'Graphics')], max_length=100),
        ),
    ]
